# Generated by Django 6.0.2 on 2026-02-08 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'markets',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'customuser',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.market')),
            ],
            options={
                'db_table': 'symbols',
            },
        ),
        migrations.CreateModel(
            name='PreciousMetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume_number', models.BigIntegerField(blank=True, null=True)),
                ('mv_score', models.IntegerField(blank=True, null=True)),
                ('cb_score', models.IntegerField(blank=True, null=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'precious_metals',
                'indexes': [models.Index(fields=['price_timestamp'], name='precious_me_price_t_4c9a16_idx'), models.Index(fields=['symbol'], name='precious_me_symbol__780b9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('rows_updated', models.IntegerField(blank=True, null=True)),
                ('time_to_execute', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.market')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'polling_logs',
                'indexes': [models.Index(fields=['created_at'], name='polling_log_created_0a3c1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternationalStocksIndexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume_number', models.BigIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('mv_score', models.IntegerField(blank=True, null=True)),
                ('cb_score', models.IntegerField(blank=True, null=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'international_stocks_indexes',
                'indexes': [models.Index(fields=['price_timestamp'], name='internation_price_t_dbd984_idx'), models.Index(fields=['symbol'], name='internation_symbol__90dee6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndiaStocksIndexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume_number', models.BigIntegerField(blank=True, null=True)),
                ('mv_score', models.IntegerField(blank=True, null=True)),
                ('cb_score', models.IntegerField(blank=True, null=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'india_stocks_indexes',
                'indexes': [models.Index(fields=['price_timestamp'], name='india_stock_price_t_25443b_idx'), models.Index(fields=['symbol'], name='india_stock_symbol__6eb738_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataPollingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(max_length=255)),
                ('market_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.market')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'data_polling_status',
                'indexes': [models.Index(fields=['status'], name='data_pollin_status_dee794_idx')],
            },
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_timestamp', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume_number', models.FloatField()),
                ('volume_usd', models.FloatField()),
                ('bitmex_funding_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('mv_score', models.IntegerField(blank=True, null=True)),
                ('cb_score', models.IntegerField(blank=True, null=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'crypto',
                'indexes': [models.Index(fields=['price_timestamp'], name='crypto_price_t_5edeb4_idx'), models.Index(fields=['symbol'], name='crypto_symbol__e716ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsStocksIndexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume_number', models.BigIntegerField(blank=True, null=True)),
                ('mv_score', models.IntegerField(blank=True, null=True)),
                ('cb_score', models.IntegerField(blank=True, null=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'us_stocks_indexes',
                'indexes': [models.Index(fields=['price_timestamp'], name='us_stocks_i_price_t_7b21cf_idx'), models.Index(fields=['symbol'], name='us_stocks_i_symbol__ce257f_idx')],
            },
        ),
    ]
