# Generated by Django 6.0.2 on 2026-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='aes_leverage_aggressive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='aes_leverage_moderate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indiastocksindexes',
            name='aes_leverage_aggressive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indiastocksindexes',
            name='aes_leverage_moderate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalstocksindexes',
            name='aes_leverage_aggressive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationalstocksindexes',
            name='aes_leverage_moderate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preciousmetals',
            name='aes_leverage_aggressive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preciousmetals',
            name='aes_leverage_moderate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usstocksindexes',
            name='aes_leverage_aggressive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usstocksindexes',
            name='aes_leverage_moderate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
